// <auto-generated />
using System;
using AuditReadyExpense.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditReadyExpense.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223182207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditReadyExpense.Domain.Expenses.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("AuditReadyExpense.Domain.Expenses.Expense", b =>
                {
                    b.OwnsMany("AuditReadyExpense.Domain.Expenses.AuditEvent", "_auditEvents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ActorUserId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FromStatus")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("OccurredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Reason")
                                .HasColumnType("text");

                            b1.Property<int>("ToStatus")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ExpenseId");

                            b1.HasIndex("OccurredAtUtc");

                            b1.ToTable("expense_audit_events", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("_auditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
